### ISSUE TITLE
Please create a new tag

### ISSUE THREAD

**Issue by cah-alexsukhodolsky** [jellekralt/angular-drag-scroll#2]
The currently tagged version of the code (0.1.0) doesn't work with the latest version of angular. Specifically, it's missing the '[]'/requires list parameter in the module definition:

.module('ng-drag-scroll', [])

Please tag your latest version so bower install can grab the newest version that includes the requires list.

Otherwise, this a great and simple directive! Great work!

Thanks,
Alex

**Comment by jellekralt** [comment]
Good point! I've bumped the version to 0.1.1 both as a release/tag on github and in the npm/bower package.
