### ISSUE TITLE
Cannot read property "split" of undefined

### ISSUE THREAD

**Issue by kdoggthebus** [jellekralt/angular-drag-scroll#4]
Error at line 23 of ng-drag-scroll.js:

`var excludedClasses = $attributes.dragScrollExcludedClasses.split(',') || false;
`
if no dragScrollExcludedClasses attribute is present, Chrome gives an error. Doesn't affect much, just figured I'd point it out.

Good directive!

**Comment by kevinthr** [comment]
+1 :(

**Comment by jellekralt** [comment]
This should now be fixed in v0.2.0
